#!/bin/bash

BASEDIR="/u/apps/simulscribe/current"
start() {
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" && rvm use ree-1.8.7-2012.02
  cd $BASEDIR && RAILS_ENV=#RAILS_ENV# ruby ./script/workling_starling_client start
}

stop() {
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" && rvm use ree-1.8.7-2012.02
  cd $BASEDIR && RAILS_ENV=#RAILS_ENV# ruby ./script/workling_starling_client stop
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 2
        start
        ;;
*)
        echo $"Usage: $0 {start|stop|restart}"
esac
exit 0
