#!/bin/bash

BASEDIR="/u/apps/simulscribe/current"
RAILS_ENV="#RAILS_ENV#"
start() {
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" && rvm use ree-1.8.7-2011.03
  RAILS_ENV=$RAILS_ENV RAGI=true RAGI_PORT=4579 mongrel_rails start --environment $RAILS_ENV --chdir $BASEDIR --port 3039 --pid $BASEDIR/log/ragi-server-9.pid --user ss --group ss --daemonize
}

stop() {
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" && rvm use ree-1.8.7-2011.03
  mongrel_rails stop --chdir $BASEDIR --pid $BASEDIR/log/ragi-server-9.pid
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 2
        start
        ;;
*)
        echo $"Usage: $0 {start|stop|restart}"
esac
exit 0
