#!/bin/bash

BASEDIR="/u/apps/simulscribe/current"
start() {
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" && rvm use ree-1.8.7-2011.03
  starling -q $BASEDIR/log -h 0.0.0.0 -p 22122 -P $BASEDIR/log/starling.pid -l $BASEDIR/log/starling.log -d
}

stop() {
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" && rvm use ree-1.8.7-2011.03
  kill -9 `cat $BASEDIR/log/starling.pid`
  rm -f $BASEDIR/log/starling.pid
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 2
        start
        ;;
*)
        echo $"Usage: $0 {start|stop|restart}"
esac
exit 0
